version: "3.1"

services:
  php-apache:
    container_name: ${PROJECT_NAME}_app_${VERSION_ID}
    build:
      context: ./docker/php-apache
      args:
        - XDEBUG=${XDEBUG}
    ports:
      - ${APACHE_PORT_EXPOSED}:80
    networks:
      - backend
      - frontend
    environment:
      APP_URL: ${APP_URL}
      TIME_ZONE: ${TIME_ZONE}
      MYSQL_HOST: mysql:${MYSQL_PORT_EXPOSED}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASS: ${MYSQL_PASS}
      MYSQL_DB: ${MYSQL_DB}
    volumes:
      - ./app:/var/www/html:cached
      - ./logs/app:/var/log/apache2
    depends_on:
      - mysql

  mysql:
    container_name: ${PROJECT_NAME}_db_${VERSION_ID}
    build:
      context: ./docker/mysql
      args:
        - DB_USER=${DB_USER}
        - DB_GROUP=${DB_GROUP}
    ports:
      - ${MYSQL_PORT_EXPOSED}:3306
    volumes:
      - ./logs/db:/var/log/mysql
      - ./db:/var/lib/mysql
    networks:
      - backend
    environment:
      TZ: ${TIME_ZONE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOTPASS}
      MYSQL_ROOT_HOST: "%"
      MYSQL_DATABASE: ${MYSQL_DB}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASS}

networks:
  frontend:
  backend: