version: "3.1"

services:
  web:
    container_name: ${PROJECT_NAME}_app_${VERSION_ID}
    build:
      context: ./docker/php-apache
      args:
        - XDEBUG=${XDEBUG}
    ports:
      - ${APACHE_PORT_EXPOSED}:80
    networks:
      - backend
      - frontend
    environment:
      APP_URL: ${APP_URL}
      TIME_ZONE: ${TIME_ZONE}
      DB_HOST: db:${DB_PORT_EXPOSED}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      DB_NAME: ${DB_NAME}
    volumes:
      - ./app:/app:cached
      - ./logs/app:/var/log/apache2
    depends_on:
      - db

  db:
    container_name: ${PROJECT_NAME}_db_${VERSION_ID}
    build:
      context: ./docker/mysql
      args:
        - DB_USER=${DB_USER}
        - DB_GROUP=${DB_GROUP}
    ports:
      - ${DB_PORT_EXPOSED}:3306
    volumes:
      - ./logs/db:/var/log/mysql
      - ./db/${DB_NAME}:/var/lib/mysql/${DB_NAME}
      # - ./docker/mysql/init:/docker-entrypoint-initdb.d
    networks:
      - backend
    environment:
      TZ: ${TIME_ZONE}
      MYSQL_ROOT_PASSWORD: ${DB_ROOTPASS}
      MYSQL_ROOT_HOST: "%"
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}

networks:
  frontend:
  backend: